server:
  port: 8080

spring:
  application:
    name: pilotes-app
  datasource: 
    url: jdbc:h2:mem:pilotesdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
  h2: 
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
springdoc:
  swagger-ui:
    path: /swagger-ui.html